# .gitlab-ci.yml

# Stages definition of the pipeline
stages:
  - deploy

# ----------------------------------------------------
# TEMPLATE
# ----------------------------------------------------
.deploy_template:
  image: alpine:latest
  stage: deploy
  script: |
    echo "Updating Alpine packages and installing core tools..."
    apk update && apk add rsync bash openssh-client
    
    if [ "$DEPLOY_TYPE" = "SSH" ]; then
        echo "--> Using SSH/external rsync to ${DEPLOY_TARGET}";

        # 1. Define variable
        KEY_FILE="${SSH_KEY_TO_USE}";
    
        # 2. SSH Key Setup
        eval $(ssh-agent -s);
        chmod 600 ${KEY_FILE};
        ssh-add ${KEY_FILE};
        
        # 3. SSH Config Setup (same as before)
        mkdir -p ~/.ssh;
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config;
    
        DEPLOY_PATH="${DEPLOY_TARGET}"; 
    elif [ "$DEPLOY_TYPE" = "LOCAL" ]; then
        echo "--> Using local rsync (mount volume) to ${LOCAL_PATH}";
        # Tidak perlu setup SSH/Key, langsung ke path mount point
        DEPLOY_PATH="${LOCAL_PATH}"; 
        
    else
        echo "ERROR: Unknown DEPLOY_TYPE variable value. Pipeline failed.";
        exit 1;
    fi
      
    # 4. Do rsync (no deletion for now)
    echo "Starting rsync deployment..."
    rsync -vz --no-times --exclude '.gitlab-ci.yml' --exclude '.git/' --exclude '__MACOSX/' ./ ${DEPLOY_PATH}

    if [ "$DEPLOY_TYPE" = "SSH" ]; then
        echo "Cleaning up SSH Key..."
        rm ${KEY_FILE};
    fi
  # These variables will be overridden by the job (dev/main)
  variables:
    DEPLOY_TYPE: ""
    DEPLOY_TARGET: ""
    SSH_KEY_TO_USE: ""
    LOCAL_PATH: ""
  tags:
  - cicd

# ----------------------------------------------------
# DEPLOY JOB TO DEV SERVER (DEV BRANCH)
# ----------------------------------------------------
deploy_dev:
  extends: .deploy_template
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  variables:
    DEPLOY_TYPE: "LOCAL"
    LOCAL_PATH: "${TARGET_DIR_DEV}"


# ----------------------------------------------------
# DEPLOY JOB TO LIVE SERVER (MAIN BRANCH)
# ----------------------------------------------------
deploy_main:
  extends: .deploy_template
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    DEPLOY_TYPE: "SSH"
    DEPLOY_TARGET: "${LIVE_SERVER_USER_HOST}:${TARGET_DIR_LIVE}"
    SSH_KEY_TO_USE: "${LIVE_SSH_PRIVATE_KEY}"
